indent = 4
margin = 120
always_for_in = true
remove_extra_newlines = true
#import_to_using = true
pipe_to_function_call = true
long_to_short_function_def = true
#format_docstrings = true
normalize_line_endings = "unix"
separate_kwargs_with_semicolon = true
